In [1]:
import json
import math
import pandas as pd
with open('master.json') as data_file:    
    data = json.load(data_file)

In [2]:
pretty_data = pd.DataFrame(data)
pretty_data= pretty_data.rename(columns = {'consult date':'request date'})
pretty_data.head()

airline      arrival request date           departure departure date  \
0  Interjet  , Monterrey   11/05/2018  , Ciudad de México     29/08/2018   
1  Interjet  , Monterrey   11/05/2018  , Ciudad de México     29/08/2018   
2  Interjet  , Monterrey   11/05/2018  , Ciudad de México     29/08/2018   
3  Interjet  , Monterrey   11/05/2018  , Ciudad de México     29/08/2018   
4  Interjet  , Monterrey   11/05/2018  , Ciudad de México     29/08/2018   

             flight duration stops  ticket price  
0  0 days 1 hours 40 minutes     0         991.0  
1  0 days 1 hours 30 minutes     0         991.0  
2  0 days 1 hours 35 minutes     0         991.0  
3  0 days 1 hours 30 minutes     0         991.0  
4  0 days 1 hours 30 minutes     0         991.0

In [3]:
just_flightDuration = pretty_data["flight duration"]
new_fD = []
for i in range(0,len(just_flightDuration)):
    temp = just_flightDuration[i].split()
    total_time = 0
    
    for j in range(0, math.ceil(len(temp)/2)):   
        if j == 0: 
            total_time += 1440*float(temp[j])
        elif j == 1:
            total_time += 60*float(temp[2*j])
        else:
            total_time += float(temp[2*j])
    new_fD.append(total_time)

In [4]:
new_flightD = pd.DataFrame(data= new_fD,columns=['flight duration']);

In [5]:
depart_dates = pretty_data['departure date']
request_dates = pretty_data['request date']
from datetime import datetime
date_format = "%d/%m/%Y"
anticipation = []
for i in range(len(depart_dates)):
    a = datetime.strptime(depart_dates[i], date_format)
    b = datetime.strptime(request_dates[i], date_format)
    delta = a - b
    anticipation.append(abs(delta.days))
pretty_data = pretty_data.drop(['departure date','request date'],axis = 1)

In [6]:
pretty_data['days of anticipation']= pd.DataFrame(data = anticipation, columns=['days of anticipation'])
pretty_data['flight duration'] = new_fD

In [7]:
cols_to_norm = ['flight duration']
pretty_data[cols_to_norm] = pretty_data[cols_to_norm].apply(lambda x: (x - x.min()) / (x.max() - x.min()))

In [7]:
clean_stops = {"stops": {"4 Stop": 4, "3 Stop": 3, 
                         "2 Stop": 2, "1 Stop": 1, 
                         "Nonstop": 0}}
pretty_data.replace(clean_stops, inplace=True)


In [8]:
pretty_data = pretty_data.drop('airline',axis = 1)

In [9]:
pretty_data = pretty_data.drop('arrival',axis = 1)
pretty_data = pretty_data.drop('departure', axis = 1)
pretty_data

flight duration stops  ticket price  days of anticipation
0                100.0     0        991.00                   110
1                 90.0     0        991.00                   110
2                 95.0     0        991.00                   110
3                 90.0     0        991.00                   110
4                 90.0     0        991.00                   110
5                 95.0     0        991.00                   110
6                 95.0     0        991.00                   110
7                 95.0     0        991.00                   110
8                 95.0     0        991.00                   110
9                 95.0     0        991.00                   110
10                95.0     0        991.00                   110
11                95.0     0        991.00                   110
12               100.0     0       1117.95                   110
13                95.0     0       1117.95                   110
14               100.0     0       1117.95                   110
15               100.0     0       1138.97                   110
16               100.0     0       1138.97                   110
17               105.0     0       1138.97                   110
18               105.0     0       1138.97                   110
19                95.0     0       1138.97                   110
20               107.0     0       1177.00                   110
21               107.0     0       1177.00                   110
22               107.0     0       1177.00                   110
23               108.0     0       1177.00                   110
24               107.0     0       1177.00                   110
25               100.0     0       1792.00                   110
26                97.0     0       1792.00                   110
27               107.0     0       1792.00                   110
28               103.0     0       1792.00                   110
29               100.0     0       1792.00                   110
...                ...   ...           ...                   ...
22526            552.0     1       8370.00                   183
22527            631.0     1       8370.00                   183
22528           1922.0     1       8370.00                   183
22529            529.0     1       8370.00                   183
22530            399.0     1       8370.00                   183
22531           2147.0     2       8370.00                   183
22532            518.0     1       8370.00                   183
22533            402.0     1       8370.00                   183
22534           2147.0     2       8370.00                   183
22535           2147.0     2       8370.00                   183
22536            427.0     1       8370.00                   183
22537            585.0     1       8370.00                   183
22538            402.0     1       8370.00                   183
22539            558.0     1       8370.00                   183
22540            729.0     2       8370.00                   183
22541            507.0     1       8370.00                   183
22542            695.0     1       8370.00                   183
22543            432.0     1       8370.00                   183
22544            596.0     2       8370.00                   183
22545            549.0     1       8370.00                   183
22546            585.0     1       8370.00                   183
22547            387.0     1       8370.00                   183
22548            751.0     2       8370.00                   183
22549            584.0     2       8370.00                   183
22550            735.0     2       8370.00                   183
22551            538.0     1       8370.00                   183
22552            541.0     1       8370.00                   183
22553            433.0     1       8370.00                   183
22554            517.0     1       8370.00                   183
22555            584.0     2       8370.00

In [10]:
pretty_data.columns = pretty_data.columns.str.replace('flight duration', 'flight_duration')
pretty_data.columns = pretty_data.columns.str.replace('ticket price', 'ticket_price')
pretty_data.columns = pretty_data.columns.str.replace('days of anticipation', 'days_of_anticipation')
pretty_data.head()
pretty_data['ticket_price']=pretty_data['ticket_price'].astype('float')
pretty_data['days_of_anticipation']=pretty_data['days_of_anticipation'].astype('float')
pretty_data['stops']=pretty_data['stops'].astype('float')

In [11]:
import tensorflow as tf

In [12]:
x_data = pretty_data.drop('ticket_price', axis = 1)
y_val = pretty_data['ticket_price']

## Create train and test sets

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
X_train, X_test, y_train, y_test = train_test_split(x_data, y_val, test_size=0.3)

In [15]:
x_data.columns

Index(['flight_duration', 'stops', 'days_of_anticipation'], dtype='object')

## Create continuous features

In [16]:
flight_duration = tf.feature_column.numeric_column('flight_duration')
stops = tf.feature_column.numeric_column('stops')
doa = tf.feature_column.numeric_column('days_of_anticipation')


## Create categorical features

In [17]:
#airl = tf.feature_column.categorical_column_with_hash_bucket('airline',hash_bucket_size=30)

## Concatenate them together

In [18]:
#feat_cols = [tf.feature_column.embedding_column(airl,9), flight_duration, stops, doa]
feat_cols = [flight_duration,stops,doa]
feat_cols

[_NumericColumn(key='flight_duration', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 _NumericColumn(key='stops', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 _NumericColumn(key='days_of_anticipation', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None)]

In [19]:
input_func = tf.estimator.inputs.pandas_input_fn(x=X_train,y=y_train,
                                                 batch_size=100,
                                                 num_epochs=1000,
                                                 shuffle=True)

In [20]:
model = tf.estimator.DNNRegressor(hidden_units = [4,4,4],
                                  feature_columns= feat_cols)
model2 = tf.estimator.LinearRegressor(feature_columns=feat_cols)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': 'C:\\Users\\guill\\AppData\\Local\\Temp\\tmpmalqqpav', '_keep_checkpoint_every_n_hours': 10000, '_session_config': None, '_keep_checkpoint_max': 5, '_save_summary_steps': 100, '_save_checkpoints_secs': 600, '_tf_random_seed': 1, '_log_step_count_steps': 100, '_save_checkpoints_steps': None}
INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': 'C:\\Users\\guill\\AppData\\Local\\Temp\\tmpmt8ewkst', '_keep_checkpoint_every_n_hours': 10000, '_session_config': None, '_keep_checkpoint_max': 5, '_save_summary_steps': 100, '_save_checkpoints_secs': 600, '_tf_random_seed': 1, '_log_step_count_steps': 100, '_save_checkpoints_steps': None}


In [21]:
model.train(input_fn = input_func, steps = 100000)

INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Saving checkpoints for 1 into C:\Users\guill\AppData\Local\Temp\tmpmalqqpav\model.ckpt.
INFO:tensorflow:loss = 5.76992e+10, step = 1
INFO:tensorflow:global_step/sec: 608.945
INFO:tensorflow:loss = 1.62367e+10, step = 101 (0.164 sec)
INFO:tensorflow:global_step/sec: 780.208
INFO:tensorflow:loss = 2.02675e+10, step = 201 (0.128 sec)
INFO:tensorflow:global_step/sec: 756.57
INFO:tensorflow:loss = 7.8028e+09, step = 301 (0.132 sec)
INFO:tensorflow:global_step/sec: 713.334
INFO:tensorflow:loss = 8.38129e+09, step = 401 (0.136 sec)
INFO:tensorflow:global_step/sec: 780.212
INFO:tensorflow:loss = 1.34337e+10, step = 501 (0.132 sec)
INFO:tensorflow:global_step/sec: 693.521
INFO:tensorflow:loss = 4.49151e+10, step = 601 (0.144 sec)
INFO:tensorflow:global_step/sec: 756.569
INFO:tensorflow:loss = 9.27114e+09, step = 701 (0.132 sec)
INFO:tensorflow:global_step/sec: 780.206
INFO:tensorflow:loss = 2.84236e+10, step = 801 (0.128 sec)
INFO:tens

INFO:tensorflow:global_step/sec: 756.574
INFO:tensorflow:loss = 3.38767e+10, step = 8101 (0.132 sec)
INFO:tensorflow:global_step/sec: 734.311
INFO:tensorflow:loss = 1.60221e+10, step = 8201 (0.136 sec)
INFO:tensorflow:global_step/sec: 779.967
INFO:tensorflow:loss = 1.98342e+10, step = 8301 (0.128 sec)
INFO:tensorflow:global_step/sec: 756.798
INFO:tensorflow:loss = 2.39749e+10, step = 8401 (0.132 sec)
INFO:tensorflow:global_step/sec: 734.316
INFO:tensorflow:loss = 1.11895e+10, step = 8501 (0.136 sec)
INFO:tensorflow:global_step/sec: 756.569
INFO:tensorflow:loss = 4.35193e+10, step = 8601 (0.132 sec)
INFO:tensorflow:global_step/sec: 756.367
INFO:tensorflow:loss = 2.60794e+10, step = 8701 (0.132 sec)
INFO:tensorflow:global_step/sec: 674.934
INFO:tensorflow:loss = 2.09629e+10, step = 8801 (0.148 sec)
INFO:tensorflow:global_step/sec: 780.209
INFO:tensorflow:loss = 1.14961e+10, step = 8901 (0.128 sec)
INFO:tensorflow:global_step/sec: 657.025
INFO:tensorflow:loss = 7.31018e+09, step = 9001 (0

INFO:tensorflow:global_step/sec: 713.158
INFO:tensorflow:loss = 3.23291e+10, step = 16201 (0.136 sec)
INFO:tensorflow:global_step/sec: 713.334
INFO:tensorflow:loss = 1.26438e+11, step = 16301 (0.144 sec)
INFO:tensorflow:global_step/sec: 693.531
INFO:tensorflow:loss = 1.8287e+10, step = 16401 (0.144 sec)
INFO:tensorflow:global_step/sec: 640.151
INFO:tensorflow:loss = 1.65353e+10, step = 16501 (0.156 sec)
INFO:tensorflow:global_step/sec: 756.784
INFO:tensorflow:loss = 1.18483e+10, step = 16601 (0.132 sec)
INFO:tensorflow:global_step/sec: 756.376
INFO:tensorflow:loss = 3.90357e+10, step = 16701 (0.132 sec)
INFO:tensorflow:global_step/sec: 640.309
INFO:tensorflow:loss = 2.25707e+10, step = 16801 (0.152 sec)
INFO:tensorflow:global_step/sec: 780.208
INFO:tensorflow:loss = 1.80915e+10, step = 16901 (0.132 sec)
INFO:tensorflow:global_step/sec: 780.211
INFO:tensorflow:loss = 9.42893e+09, step = 17001 (0.128 sec)
INFO:tensorflow:global_step/sec: 805.375
INFO:tensorflow:loss = 6.7808e+10, step = 

INFO:tensorflow:global_step/sec: 756.372
INFO:tensorflow:loss = 7.30828e+09, step = 24301 (0.132 sec)
INFO:tensorflow:global_step/sec: 713.51
INFO:tensorflow:loss = 1.52239e+10, step = 24401 (0.140 sec)
INFO:tensorflow:global_step/sec: 674.778
INFO:tensorflow:loss = 1.20383e+10, step = 24501 (0.148 sec)
INFO:tensorflow:global_step/sec: 640.175
INFO:tensorflow:loss = 2.06402e+10, step = 24601 (0.156 sec)
INFO:tensorflow:global_step/sec: 756.565
INFO:tensorflow:loss = 3.77848e+10, step = 24701 (0.128 sec)
INFO:tensorflow:global_step/sec: 713.334
INFO:tensorflow:loss = 9.46856e+09, step = 24801 (0.144 sec)
INFO:tensorflow:global_step/sec: 693.526
INFO:tensorflow:loss = 4.43598e+10, step = 24901 (0.140 sec)
INFO:tensorflow:global_step/sec: 624.166
INFO:tensorflow:loss = 6.23058e+09, step = 25001 (0.160 sec)
INFO:tensorflow:global_step/sec: 780.212
INFO:tensorflow:loss = 3.80018e+10, step = 25101 (0.132 sec)
INFO:tensorflow:global_step/sec: 780.208
INFO:tensorflow:loss = 2.20107e+10, step =

INFO:tensorflow:global_step/sec: 674.77
INFO:tensorflow:loss = 5.56497e+09, step = 32401 (0.148 sec)
INFO:tensorflow:global_step/sec: 657.023
INFO:tensorflow:loss = 3.41009e+10, step = 32501 (0.152 sec)
INFO:tensorflow:global_step/sec: 580.621
INFO:tensorflow:loss = 2.84391e+10, step = 32601 (0.172 sec)
INFO:tensorflow:global_step/sec: 624.168
INFO:tensorflow:loss = 1.67364e+10, step = 32701 (0.160 sec)
INFO:tensorflow:global_step/sec: 624.168
INFO:tensorflow:loss = 2.45182e+10, step = 32801 (0.160 sec)
INFO:tensorflow:global_step/sec: 594.447
INFO:tensorflow:loss = 6.04584e+09, step = 32901 (0.164 sec)
INFO:tensorflow:global_step/sec: 713.329
INFO:tensorflow:loss = 1.26783e+10, step = 33001 (0.140 sec)
INFO:tensorflow:global_step/sec: 780.214
INFO:tensorflow:loss = 2.06187e+10, step = 33101 (0.132 sec)
INFO:tensorflow:global_step/sec: 756.572
INFO:tensorflow:loss = 1.5272e+10, step = 33201 (0.132 sec)
INFO:tensorflow:global_step/sec: 734.315
INFO:tensorflow:loss = 1.92141e+10, step = 

INFO:tensorflow:global_step/sec: 567.427
INFO:tensorflow:loss = 1.26067e+10, step = 40501 (0.176 sec)
INFO:tensorflow:global_step/sec: 693.522
INFO:tensorflow:loss = 8.6263e+10, step = 40601 (0.144 sec)
INFO:tensorflow:global_step/sec: 693.513
INFO:tensorflow:loss = 9.82942e+09, step = 40701 (0.144 sec)
INFO:tensorflow:global_step/sec: 674.782
INFO:tensorflow:loss = 4.7616e+10, step = 40801 (0.148 sec)
INFO:tensorflow:global_step/sec: 693.521
INFO:tensorflow:loss = 3.36059e+10, step = 40901 (0.144 sec)
INFO:tensorflow:global_step/sec: 693.521
INFO:tensorflow:loss = 3.24735e+10, step = 41001 (0.144 sec)
INFO:tensorflow:global_step/sec: 734.307
INFO:tensorflow:loss = 9.23509e+09, step = 41101 (0.136 sec)
INFO:tensorflow:global_step/sec: 693.527
INFO:tensorflow:loss = 3.52938e+10, step = 41201 (0.144 sec)
INFO:tensorflow:global_step/sec: 693.52
INFO:tensorflow:loss = 6.72178e+10, step = 41301 (0.144 sec)
INFO:tensorflow:global_step/sec: 693.524
INFO:tensorflow:loss = 2.3068e+10, step = 41

INFO:tensorflow:global_step/sec: 693.518
INFO:tensorflow:loss = 9.5189e+10, step = 48601 (0.140 sec)
INFO:tensorflow:global_step/sec: 734.314
INFO:tensorflow:loss = 3.28873e+10, step = 48701 (0.136 sec)
INFO:tensorflow:global_step/sec: 756.573
INFO:tensorflow:loss = 1.93951e+10, step = 48801 (0.132 sec)
INFO:tensorflow:global_step/sec: 567.422
INFO:tensorflow:loss = 1.17616e+10, step = 48901 (0.176 sec)
INFO:tensorflow:global_step/sec: 693.523
INFO:tensorflow:loss = 7.21118e+09, step = 49001 (0.144 sec)
INFO:tensorflow:global_step/sec: 657.02
INFO:tensorflow:loss = 1.56981e+10, step = 49101 (0.148 sec)
INFO:tensorflow:global_step/sec: 640.173
INFO:tensorflow:loss = 1.79336e+10, step = 49201 (0.160 sec)
INFO:tensorflow:global_step/sec: 674.764
INFO:tensorflow:loss = 2.44997e+10, step = 49301 (0.148 sec)
INFO:tensorflow:global_step/sec: 693.532
INFO:tensorflow:loss = 8.09013e+10, step = 49401 (0.144 sec)
INFO:tensorflow:global_step/sec: 734.32
INFO:tensorflow:loss = 1.04976e+10, step = 4

INFO:tensorflow:global_step/sec: 756.78
INFO:tensorflow:loss = 1.03132e+11, step = 56701 (0.132 sec)
INFO:tensorflow:global_step/sec: 734.319
INFO:tensorflow:loss = 3.10326e+10, step = 56801 (0.136 sec)
INFO:tensorflow:global_step/sec: 713.332
INFO:tensorflow:loss = 1.96615e+10, step = 56901 (0.140 sec)
INFO:tensorflow:global_step/sec: 756.57
INFO:tensorflow:loss = 8.24424e+09, step = 57001 (0.132 sec)
INFO:tensorflow:global_step/sec: 780.206
INFO:tensorflow:loss = 2.70739e+10, step = 57101 (0.128 sec)
INFO:tensorflow:global_step/sec: 780.215
INFO:tensorflow:loss = 7.2406e+10, step = 57201 (0.128 sec)
INFO:tensorflow:global_step/sec: 657.015
INFO:tensorflow:loss = 2.88616e+10, step = 57301 (0.152 sec)
INFO:tensorflow:global_step/sec: 693.524
INFO:tensorflow:loss = 8.20795e+09, step = 57401 (0.144 sec)
INFO:tensorflow:global_step/sec: 780.202
INFO:tensorflow:loss = 6.09189e+09, step = 57501 (0.128 sec)
INFO:tensorflow:global_step/sec: 734.325
INFO:tensorflow:loss = 5.22412e+10, step = 5

INFO:tensorflow:global_step/sec: 713.401
INFO:tensorflow:loss = 8.40737e+09, step = 64801 (0.140 sec)
INFO:tensorflow:global_step/sec: 734.319
INFO:tensorflow:loss = 8.3985e+09, step = 64901 (0.136 sec)
INFO:tensorflow:global_step/sec: 594.443
INFO:tensorflow:loss = 8.17161e+09, step = 65001 (0.168 sec)
INFO:tensorflow:global_step/sec: 624.157
INFO:tensorflow:loss = 2.43805e+10, step = 65101 (0.160 sec)
INFO:tensorflow:global_step/sec: 640.181
INFO:tensorflow:loss = 6.14052e+10, step = 65201 (0.156 sec)
INFO:tensorflow:global_step/sec: 640.177
INFO:tensorflow:loss = 1.56347e+10, step = 65301 (0.152 sec)
INFO:tensorflow:global_step/sec: 713.338
INFO:tensorflow:loss = 7.8233e+10, step = 65401 (0.144 sec)
INFO:tensorflow:global_step/sec: 734.307
INFO:tensorflow:loss = 5.56243e+10, step = 65501 (0.136 sec)
INFO:tensorflow:global_step/sec: 674.63
INFO:tensorflow:loss = 5.54503e+10, step = 65601 (0.148 sec)
INFO:tensorflow:global_step/sec: 713.316
INFO:tensorflow:loss = 5.89426e+10, step = 6

INFO:tensorflow:global_step/sec: 657.021
INFO:tensorflow:loss = 9.05188e+09, step = 72901 (0.156 sec)
INFO:tensorflow:global_step/sec: 713.17
INFO:tensorflow:loss = 5.90919e+09, step = 73001 (0.140 sec)
INFO:tensorflow:global_step/sec: 780.405
INFO:tensorflow:loss = 2.17135e+10, step = 73101 (0.128 sec)
INFO:tensorflow:global_step/sec: 734.314
INFO:tensorflow:loss = 5.53776e+09, step = 73201 (0.132 sec)
INFO:tensorflow:global_step/sec: 756.565
INFO:tensorflow:loss = 9.09233e+09, step = 73301 (0.136 sec)
INFO:tensorflow:global_step/sec: 756.577
INFO:tensorflow:loss = 6.56465e+09, step = 73401 (0.132 sec)
INFO:tensorflow:global_step/sec: 780.202
INFO:tensorflow:loss = 1.21952e+10, step = 73501 (0.128 sec)
INFO:tensorflow:global_step/sec: 734.314
INFO:tensorflow:loss = 4.49496e+10, step = 73601 (0.136 sec)
INFO:tensorflow:global_step/sec: 693.523
INFO:tensorflow:loss = 4.30652e+09, step = 73701 (0.144 sec)
INFO:tensorflow:global_step/sec: 674.78
INFO:tensorflow:loss = 3.28482e+10, step = 

INFO:tensorflow:global_step/sec: 640.183
INFO:tensorflow:loss = 6.70401e+09, step = 81001 (0.156 sec)
INFO:tensorflow:global_step/sec: 657.017
INFO:tensorflow:loss = 1.58296e+10, step = 81101 (0.152 sec)
INFO:tensorflow:global_step/sec: 580.623
INFO:tensorflow:loss = 1.84424e+10, step = 81201 (0.172 sec)
INFO:tensorflow:global_step/sec: 542.756
INFO:tensorflow:loss = 2.40816e+10, step = 81301 (0.184 sec)
INFO:tensorflow:global_step/sec: 756.569
INFO:tensorflow:loss = 3.1444e+10, step = 81401 (0.132 sec)
INFO:tensorflow:global_step/sec: 734.315
INFO:tensorflow:loss = 8.31064e+09, step = 81501 (0.136 sec)
INFO:tensorflow:global_step/sec: 780.199
INFO:tensorflow:loss = 5.26703e+10, step = 81601 (0.128 sec)
INFO:tensorflow:global_step/sec: 674.788
INFO:tensorflow:loss = 1.54993e+10, step = 81701 (0.148 sec)
INFO:tensorflow:global_step/sec: 734.312
INFO:tensorflow:loss = 1.51645e+10, step = 81801 (0.136 sec)
INFO:tensorflow:global_step/sec: 713.335
INFO:tensorflow:loss = 1.6434e+10, step = 

INFO:tensorflow:global_step/sec: 580.623
INFO:tensorflow:loss = 1.00987e+10, step = 89101 (0.172 sec)
INFO:tensorflow:global_step/sec: 640.172
INFO:tensorflow:loss = 5.18814e+09, step = 89201 (0.152 sec)
INFO:tensorflow:global_step/sec: 674.778
INFO:tensorflow:loss = 5.53047e+10, step = 89301 (0.152 sec)
INFO:tensorflow:global_step/sec: 554.811
INFO:tensorflow:loss = 3.46223e+10, step = 89401 (0.180 sec)
INFO:tensorflow:global_step/sec: 608.945
INFO:tensorflow:loss = 1.94313e+10, step = 89501 (0.164 sec)
INFO:tensorflow:global_step/sec: 594.451
INFO:tensorflow:loss = 1.97188e+10, step = 89601 (0.168 sec)
INFO:tensorflow:global_step/sec: 542.753
INFO:tensorflow:loss = 5.70804e+10, step = 89701 (0.180 sec)
INFO:tensorflow:global_step/sec: 542.753
INFO:tensorflow:loss = 1.62632e+10, step = 89801 (0.188 sec)
INFO:tensorflow:global_step/sec: 624.171
INFO:tensorflow:loss = 1.71757e+10, step = 89901 (0.160 sec)
INFO:tensorflow:global_step/sec: 567.323
INFO:tensorflow:loss = 2.35384e+10, step 

INFO:tensorflow:global_step/sec: 640.003
INFO:tensorflow:loss = 2.27838e+10, step = 97201 (0.152 sec)
INFO:tensorflow:global_step/sec: 640.335
INFO:tensorflow:loss = 3.83052e+10, step = 97301 (0.160 sec)
INFO:tensorflow:global_step/sec: 734.329
INFO:tensorflow:loss = 2.37594e+10, step = 97401 (0.136 sec)
INFO:tensorflow:global_step/sec: 693.514
INFO:tensorflow:loss = 6.05742e+10, step = 97501 (0.140 sec)
INFO:tensorflow:global_step/sec: 674.765
INFO:tensorflow:loss = 2.87955e+10, step = 97601 (0.152 sec)
INFO:tensorflow:global_step/sec: 693.53
INFO:tensorflow:loss = 3.49567e+10, step = 97701 (0.144 sec)
INFO:tensorflow:global_step/sec: 780.217
INFO:tensorflow:loss = 7.20287e+09, step = 97801 (0.124 sec)
INFO:tensorflow:global_step/sec: 756.569
INFO:tensorflow:loss = 1.87883e+10, step = 97901 (0.136 sec)
INFO:tensorflow:global_step/sec: 780.209
INFO:tensorflow:loss = 5.2694e+10, step = 98001 (0.128 sec)
INFO:tensorflow:global_step/sec: 674.772
INFO:tensorflow:loss = 1.8464e+10, step = 9

In [22]:
predict_input_func = tf.estimator.inputs.pandas_input_fn(x = X_test,
                                                        batch_size = 100,
                                                        num_epochs= 1,
                                                        shuffle=False)

In [43]:
pred_gen = model.predict(predict_input_func)
#X_test.head()

In [24]:
predictions = list(pred_gen)


INFO:tensorflow:Restoring parameters from C:\Users\guill\AppData\Local\Temp\tmpmalqqpav\model.ckpt-100000


In [25]:
final_preds = []

for pred in predictions: 
    final_preds.append(pred['predictions'])

In [26]:
from sklearn.metrics import mean_squared_error

In [38]:
error = mean_squared_error(y_test, final_preds)**0.5
error

15139.804366689792

In [39]:
avg_error = error/(30)
avg_error

504.66014555632643

In [40]:
final_preds[0]

array([ 16194.41113281], dtype=float32)

In [41]:
y_real_values = list(y_test)
final_preds[:10]

[array([ 16194.41113281], dtype=float32),
 array([ 4782.81738281], dtype=float32),
 array([ 8412.640625], dtype=float32),
 array([ 2432.1550293], dtype=float32),
 array([ 9405.23632812], dtype=float32),
 array([ 11387.73828125], dtype=float32),
 array([ 7445.14501953], dtype=float32),
 array([ 6274.87597656], dtype=float32),
 array([ 9213.52050781], dtype=float32),
 array([ 2113.64819336], dtype=float32)]

In [42]:
list(y_test)[:10]

[9921.4200000000001,
 4897.8000000000002,
 4736.0,
 8521.4799999999996,
 8568.0,
 3444.9299999999998,
 5574.0,
 13630.0,
 10690.0,
 1305.4499999999998]