In [1]:
import json
import math
import pandas as pd
with open('master.json') as data_file:    
    data = json.load(data_file)

In [2]:
pretty_data = pd.DataFrame(data)
pretty_data= pretty_data.rename(columns = {'consult date':'request date'})
pretty_data.head()

airline      arrival request date           departure departure date  \
0  Interjet  , Monterrey   11/05/2018  , Ciudad de México     29/08/2018   
1  Interjet  , Monterrey   11/05/2018  , Ciudad de México     29/08/2018   
2  Interjet  , Monterrey   11/05/2018  , Ciudad de México     29/08/2018   
3  Interjet  , Monterrey   11/05/2018  , Ciudad de México     29/08/2018   
4  Interjet  , Monterrey   11/05/2018  , Ciudad de México     29/08/2018   

             flight duration stops  ticket price  
0  0 days 1 hours 40 minutes     0         991.0  
1  0 days 1 hours 30 minutes     0         991.0  
2  0 days 1 hours 35 minutes     0         991.0  
3  0 days 1 hours 30 minutes     0         991.0  
4  0 days 1 hours 30 minutes     0         991.0

In [3]:
just_flightDuration = pretty_data["flight duration"]
new_fD = []
for i in range(0,len(just_flightDuration)):
    temp = just_flightDuration[i].split()
    total_time = 0
    
    for j in range(0, math.ceil(len(temp)/2)):   
        if j == 0: 
            total_time += 1440*float(temp[j])
        elif j == 1:
            total_time += 60*float(temp[2*j])
        else:
            total_time += float(temp[2*j])
    new_fD.append(total_time)

In [4]:
new_flightD = pd.DataFrame(data= new_fD,columns=['flight duration']);

In [5]:
depart_dates = pretty_data['departure date']
request_dates = pretty_data['request date']
from datetime import datetime
date_format = "%d/%m/%Y"
anticipation = []
for i in range(len(depart_dates)):
    a = datetime.strptime(depart_dates[i], date_format)
    b = datetime.strptime(request_dates[i], date_format)
    delta = a - b
    anticipation.append(abs(delta.days))
pretty_data = pretty_data.drop(['departure date','request date'],axis = 1)

In [6]:
pretty_data['days of anticipation']= pd.DataFrame(data = anticipation, columns=['days of anticipation'])
pretty_data['flight duration'] = new_fD

In [7]:
cols_to_norm = ['flight duration']
pretty_data[cols_to_norm] = pretty_data[cols_to_norm].apply(lambda x: (x - x.min()) / (x.max() - x.min()))

In [8]:
clean_stops = {"stops": {"4 Stop": 4, "3 Stop": 3, 
                         "2 Stop": 2, "1 Stop": 1, 
                         "Nonstop": 0}}
pretty_data.replace(clean_stops, inplace=True)


In [9]:
pretty_data = pretty_data.drop('airline',axis = 1)

In [10]:
pretty_data = pretty_data.drop('arrival',axis = 1)
pretty_data = pretty_data.drop('departure', axis = 1)
pretty_data

flight duration stops  ticket price  days of anticipation
0             0.021525     0        991.00                   110
1             0.018450     0        991.00                   110
2             0.019988     0        991.00                   110
3             0.018450     0        991.00                   110
4             0.018450     0        991.00                   110
5             0.019988     0        991.00                   110
6             0.019988     0        991.00                   110
7             0.019988     0        991.00                   110
8             0.019988     0        991.00                   110
9             0.019988     0        991.00                   110
10            0.019988     0        991.00                   110
11            0.019988     0        991.00                   110
12            0.021525     0       1117.95                   110
13            0.019988     0       1117.95                   110
14            0.021525     0       1117.95                   110
15            0.021525     0       1138.97                   110
16            0.021525     0       1138.97                   110
17            0.023063     0       1138.97                   110
18            0.023063     0       1138.97                   110
19            0.019988     0       1138.97                   110
20            0.023678     0       1177.00                   110
21            0.023678     0       1177.00                   110
22            0.023678     0       1177.00                   110
23            0.023985     0       1177.00                   110
24            0.023678     0       1177.00                   110
25            0.021525     0       1792.00                   110
26            0.020603     0       1792.00                   110
27            0.023678     0       1792.00                   110
28            0.022448     0       1792.00                   110
29            0.021525     0       1792.00                   110
...                ...   ...           ...                   ...
22526         0.160517     1       8370.00                   183
22527         0.184809     1       8370.00                   183
22528         0.581796     1       8370.00                   183
22529         0.153444     1       8370.00                   183
22530         0.113469     1       8370.00                   183
22531         0.650984     2       8370.00                   183
22532         0.150062     1       8370.00                   183
22533         0.114391     1       8370.00                   183
22534         0.650984     2       8370.00                   183
22535         0.650984     2       8370.00                   183
22536         0.122079     1       8370.00                   183
22537         0.170664     1       8370.00                   183
22538         0.114391     1       8370.00                   183
22539         0.162362     1       8370.00                   183
22540         0.214945     2       8370.00                   183
22541         0.146679     1       8370.00                   183
22542         0.204490     1       8370.00                   183
22543         0.123616     1       8370.00                   183
22544         0.174047     2       8370.00                   183
22545         0.159594     1       8370.00                   183
22546         0.170664     1       8370.00                   183
22547         0.109779     1       8370.00                   183
22548         0.221710     2       8370.00                   183
22549         0.170357     2       8370.00                   183
22550         0.216790     2       8370.00                   183
22551         0.156212     1       8370.00                   183
22552         0.157134     1       8370.00                   183
22553         0.123924     1       8370.00                   183
22554         0.149754     1       8370.00                   183
22555         0.170357     2       8370.00

In [11]:
pretty_data.columns = pretty_data.columns.str.replace('flight duration', 'flight_duration')
pretty_data.columns = pretty_data.columns.str.replace('ticket price', 'ticket_price')
pretty_data.columns = pretty_data.columns.str.replace('days of anticipation', 'days_of_anticipation')
pretty_data.head()
pretty_data['ticket_price']=pretty_data['ticket_price'].astype('float')
pretty_data['days_of_anticipation']=pretty_data['days_of_anticipation'].astype('float')
pretty_data['stops']=pretty_data['stops'].astype('float')

In [12]:
import tensorflow as tf

In [13]:
x_data = pretty_data.drop('ticket_price', axis = 1)
y_val = pretty_data['ticket_price']

## Create train and test sets

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
X_train, X_test, y_train, y_test = train_test_split(x_data, y_val, test_size=0.3)

In [16]:
x_data.columns

Index(['flight_duration', 'stops', 'days_of_anticipation'], dtype='object')

## Create continuous features

In [17]:
flight_duration = tf.feature_column.numeric_column('flight_duration')
stops = tf.feature_column.numeric_column('stops')
doa = tf.feature_column.numeric_column('days_of_anticipation')


## Create categorical features

In [18]:
#airl = tf.feature_column.categorical_column_with_hash_bucket('airline',hash_bucket_size=30)

## Concatenate them together

In [128]:
#feat_cols = [tf.feature_column.embedding_column(airl,9), flight_duration, stops, doa]
feat_cols = [flight_duration,stops,doa]
feat_cols

[_NumericColumn(key='flight_duration', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 _NumericColumn(key='stops', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 _NumericColumn(key='days_of_anticipation', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None)]

In [142]:
input_func = tf.estimator.inputs.pandas_input_fn(x=X_train,y=y_train,
                                                 batch_size=100,
                                                 num_epochs=1000,
                                                 shuffle=True)

In [155]:
model = tf.estimator.DNNRegressor(hidden_units = [4,4,4],
                                  feature_columns= feat_cols)
model2 = tf.estimator.LinearRegressor(feature_columns=feat_cols)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_save_summary_steps': 100, '_model_dir': 'C:\\Users\\guill\\AppData\\Local\\Temp\\tmp7icm9e2u', '_keep_checkpoint_every_n_hours': 10000, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_log_step_count_steps': 100, '_tf_random_seed': 1, '_keep_checkpoint_max': 5}
INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_save_summary_steps': 100, '_model_dir': 'C:\\Users\\guill\\AppData\\Local\\Temp\\tmpbeoanc3a', '_keep_checkpoint_every_n_hours': 10000, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_log_step_count_steps': 100, '_tf_random_seed': 1, '_keep_checkpoint_max': 5}


In [144]:
model.train(input_fn = input_func, steps = 100000)

INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Saving checkpoints for 1 into C:\Users\guill\AppData\Local\Temp\tmpjd2_6urx\model.ckpt.
INFO:tensorflow:loss = 1.64501e+10, step = 1
INFO:tensorflow:global_step/sec: 542.66
INFO:tensorflow:loss = 1.36785e+10, step = 101 (0.188 sec)
INFO:tensorflow:global_step/sec: 594.557
INFO:tensorflow:loss = 1.91575e+10, step = 201 (0.168 sec)
INFO:tensorflow:global_step/sec: 640.175
INFO:tensorflow:loss = 1.51107e+10, step = 301 (0.156 sec)
INFO:tensorflow:global_step/sec: 580.62
INFO:tensorflow:loss = 1.375e+10, step = 401 (0.172 sec)
INFO:tensorflow:global_step/sec: 542.755
INFO:tensorflow:loss = 1.56982e+10, step = 501 (0.180 sec)
INFO:tensorflow:global_step/sec: 713.336
INFO:tensorflow:loss = 1.87875e+10, step = 601 (0.144 sec)
INFO:tensorflow:global_step/sec: 554.809
INFO:tensorflow:loss = 1.88002e+10, step = 701 (0.180 sec)
INFO:tensorflow:global_step/sec: 657.026
INFO:tensorflow:loss = 1.92656e+10, step = 801 (0.152 sec)
INFO:tensor

INFO:tensorflow:global_step/sec: 567.428
INFO:tensorflow:loss = 5.22775e+10, step = 8101 (0.176 sec)
INFO:tensorflow:global_step/sec: 567.42
INFO:tensorflow:loss = 1.46348e+10, step = 8201 (0.180 sec)
INFO:tensorflow:global_step/sec: 608.952
INFO:tensorflow:loss = 9.28416e+09, step = 8301 (0.164 sec)
INFO:tensorflow:global_step/sec: 624.166
INFO:tensorflow:loss = 7.01916e+10, step = 8401 (0.160 sec)
INFO:tensorflow:global_step/sec: 624.16
INFO:tensorflow:loss = 1.12476e+10, step = 8501 (0.160 sec)
INFO:tensorflow:global_step/sec: 756.58
INFO:tensorflow:loss = 1.35401e+10, step = 8601 (0.132 sec)
INFO:tensorflow:global_step/sec: 567.269
INFO:tensorflow:loss = 1.05346e+10, step = 8701 (0.176 sec)
INFO:tensorflow:global_step/sec: 713.577
INFO:tensorflow:loss = 6.75094e+09, step = 8801 (0.140 sec)
INFO:tensorflow:global_step/sec: 656.975
INFO:tensorflow:loss = 1.22248e+10, step = 8901 (0.152 sec)
INFO:tensorflow:global_step/sec: 567.461
INFO:tensorflow:loss = 1.00133e+10, step = 9001 (0.17

INFO:tensorflow:global_step/sec: 594.447
INFO:tensorflow:loss = 2.45109e+10, step = 16201 (0.172 sec)
INFO:tensorflow:global_step/sec: 580.617
INFO:tensorflow:loss = 1.33544e+10, step = 16301 (0.172 sec)
INFO:tensorflow:global_step/sec: 554.82
INFO:tensorflow:loss = 3.61608e+10, step = 16401 (0.176 sec)
INFO:tensorflow:global_step/sec: 580.563
INFO:tensorflow:loss = 6.26084e+09, step = 16501 (0.172 sec)
INFO:tensorflow:global_step/sec: 567.376
INFO:tensorflow:loss = 1.49255e+10, step = 16601 (0.176 sec)
INFO:tensorflow:global_step/sec: 567.529
INFO:tensorflow:loss = 8.63906e+09, step = 16701 (0.176 sec)
INFO:tensorflow:global_step/sec: 567.421
INFO:tensorflow:loss = 1.23631e+10, step = 16801 (0.176 sec)
INFO:tensorflow:global_step/sec: 640.165
INFO:tensorflow:loss = 9.90847e+09, step = 16901 (0.160 sec)
INFO:tensorflow:global_step/sec: 674.789
INFO:tensorflow:loss = 1.43541e+10, step = 17001 (0.144 sec)
INFO:tensorflow:global_step/sec: 567.324
INFO:tensorflow:loss = 1.05278e+10, step =

INFO:tensorflow:global_step/sec: 567.433
INFO:tensorflow:loss = 1.68883e+10, step = 24301 (0.176 sec)
INFO:tensorflow:global_step/sec: 567.426
INFO:tensorflow:loss = 2.81244e+10, step = 24401 (0.176 sec)
INFO:tensorflow:global_step/sec: 567.424
INFO:tensorflow:loss = 1.18751e+10, step = 24501 (0.176 sec)
INFO:tensorflow:global_step/sec: 640.121
INFO:tensorflow:loss = 3.89092e+09, step = 24601 (0.156 sec)
INFO:tensorflow:global_step/sec: 756.431
INFO:tensorflow:loss = 5.38387e+10, step = 24701 (0.132 sec)
INFO:tensorflow:global_step/sec: 567.543
INFO:tensorflow:loss = 2.55633e+10, step = 24801 (0.176 sec)
INFO:tensorflow:global_step/sec: 567.313
INFO:tensorflow:loss = 3.76219e+10, step = 24901 (0.176 sec)
INFO:tensorflow:global_step/sec: 567.537
INFO:tensorflow:loss = 2.39458e+10, step = 25001 (0.176 sec)
INFO:tensorflow:global_step/sec: 567.424
INFO:tensorflow:loss = 9.068e+09, step = 25101 (0.172 sec)
INFO:tensorflow:global_step/sec: 619.413
INFO:tensorflow:loss = 9.23054e+09, step = 

INFO:tensorflow:global_step/sec: 567.53
INFO:tensorflow:loss = 2.32358e+10, step = 32401 (0.176 sec)
INFO:tensorflow:global_step/sec: 657.018
INFO:tensorflow:loss = 9.79626e+09, step = 32501 (0.152 sec)
INFO:tensorflow:global_step/sec: 580.625
INFO:tensorflow:loss = 2.05319e+10, step = 32601 (0.172 sec)
INFO:tensorflow:global_step/sec: 674.768
INFO:tensorflow:loss = 7.96785e+09, step = 32701 (0.148 sec)
INFO:tensorflow:global_step/sec: 640.176
INFO:tensorflow:loss = 2.7463e+10, step = 32801 (0.156 sec)
INFO:tensorflow:global_step/sec: 657.016
INFO:tensorflow:loss = 1.09873e+10, step = 32901 (0.152 sec)
INFO:tensorflow:global_step/sec: 567.43
INFO:tensorflow:loss = 2.50763e+10, step = 33001 (0.176 sec)
INFO:tensorflow:global_step/sec: 567.304
INFO:tensorflow:loss = 1.49158e+10, step = 33101 (0.176 sec)
INFO:tensorflow:global_step/sec: 567.439
INFO:tensorflow:loss = 4.09852e+10, step = 33201 (0.176 sec)
INFO:tensorflow:global_step/sec: 674.927
INFO:tensorflow:loss = 8.94761e+09, step = 3

INFO:tensorflow:global_step/sec: 567.531
INFO:tensorflow:loss = 3.36355e+10, step = 40501 (0.176 sec)
INFO:tensorflow:global_step/sec: 594.438
INFO:tensorflow:loss = 1.88185e+10, step = 40601 (0.164 sec)
INFO:tensorflow:global_step/sec: 567.431
INFO:tensorflow:loss = 9.71018e+09, step = 40701 (0.176 sec)
INFO:tensorflow:global_step/sec: 567.418
INFO:tensorflow:loss = 4.89238e+10, step = 40801 (0.180 sec)
INFO:tensorflow:global_step/sec: 580.626
INFO:tensorflow:loss = 1.98239e+10, step = 40901 (0.168 sec)
INFO:tensorflow:global_step/sec: 567.422
INFO:tensorflow:loss = 4.73512e+09, step = 41001 (0.180 sec)
INFO:tensorflow:global_step/sec: 567.43
INFO:tensorflow:loss = 3.17914e+10, step = 41101 (0.176 sec)
INFO:tensorflow:global_step/sec: 567.287
INFO:tensorflow:loss = 9.61101e+09, step = 41201 (0.172 sec)
INFO:tensorflow:global_step/sec: 567.562
INFO:tensorflow:loss = 1.6934e+10, step = 41301 (0.176 sec)
INFO:tensorflow:global_step/sec: 567.425
INFO:tensorflow:loss = 2.76433e+10, step = 

INFO:tensorflow:global_step/sec: 756.569
INFO:tensorflow:loss = 2.85219e+10, step = 48601 (0.132 sec)
INFO:tensorflow:global_step/sec: 780.199
INFO:tensorflow:loss = 2.64426e+10, step = 48701 (0.128 sec)
INFO:tensorflow:global_step/sec: 780.218
INFO:tensorflow:loss = 9.30251e+10, step = 48801 (0.124 sec)
INFO:tensorflow:global_step/sec: 832.211
INFO:tensorflow:loss = 1.79814e+10, step = 48901 (0.124 sec)
INFO:tensorflow:global_step/sec: 805.393
INFO:tensorflow:loss = 1.81512e+10, step = 49001 (0.120 sec)
INFO:tensorflow:global_step/sec: 756.562
INFO:tensorflow:loss = 3.95079e+09, step = 49101 (0.136 sec)
INFO:tensorflow:global_step/sec: 640.17
INFO:tensorflow:loss = 4.04815e+09, step = 49201 (0.152 sec)
INFO:tensorflow:global_step/sec: 693.522
INFO:tensorflow:loss = 6.1411e+09, step = 49301 (0.144 sec)
INFO:tensorflow:global_step/sec: 756.567
INFO:tensorflow:loss = 9.53345e+09, step = 49401 (0.136 sec)
INFO:tensorflow:global_step/sec: 779.992
INFO:tensorflow:loss = 1.57474e+10, step = 

INFO:tensorflow:global_step/sec: 780.208
INFO:tensorflow:loss = 1.08929e+10, step = 56701 (0.132 sec)
INFO:tensorflow:global_step/sec: 734.319
INFO:tensorflow:loss = 5.6768e+09, step = 56801 (0.132 sec)
INFO:tensorflow:global_step/sec: 780.211
INFO:tensorflow:loss = 3.17715e+10, step = 56901 (0.132 sec)
INFO:tensorflow:global_step/sec: 780.209
INFO:tensorflow:loss = 1.64119e+10, step = 57001 (0.128 sec)
INFO:tensorflow:global_step/sec: 780.208
INFO:tensorflow:loss = 8.76359e+09, step = 57101 (0.128 sec)
INFO:tensorflow:global_step/sec: 756.351
INFO:tensorflow:loss = 6.44162e+09, step = 57201 (0.128 sec)
INFO:tensorflow:global_step/sec: 780.436
INFO:tensorflow:loss = 7.02819e+09, step = 57301 (0.132 sec)
INFO:tensorflow:global_step/sec: 780.212
INFO:tensorflow:loss = 7.50478e+09, step = 57401 (0.124 sec)
INFO:tensorflow:global_step/sec: 805.373
INFO:tensorflow:loss = 5.44866e+09, step = 57501 (0.128 sec)
INFO:tensorflow:global_step/sec: 756.573
INFO:tensorflow:loss = 8.57944e+10, step =

INFO:tensorflow:global_step/sec: 780.214
INFO:tensorflow:loss = 2.87028e+10, step = 64801 (0.128 sec)
INFO:tensorflow:global_step/sec: 756.562
INFO:tensorflow:loss = 6.30378e+09, step = 64901 (0.132 sec)
INFO:tensorflow:global_step/sec: 780.218
INFO:tensorflow:loss = 4.5913e+09, step = 65001 (0.128 sec)
INFO:tensorflow:global_step/sec: 756.558
INFO:tensorflow:loss = 6.86028e+09, step = 65101 (0.132 sec)
INFO:tensorflow:global_step/sec: 756.378
INFO:tensorflow:loss = 6.09672e+09, step = 65201 (0.132 sec)
INFO:tensorflow:global_step/sec: 780.415
INFO:tensorflow:loss = 1.65719e+10, step = 65301 (0.124 sec)
INFO:tensorflow:global_step/sec: 780.209
INFO:tensorflow:loss = 4.23253e+10, step = 65401 (0.132 sec)
INFO:tensorflow:global_step/sec: 780.003
INFO:tensorflow:loss = 5.20518e+09, step = 65501 (0.124 sec)
INFO:tensorflow:global_step/sec: 805.375
INFO:tensorflow:loss = 7.84618e+09, step = 65601 (0.128 sec)
INFO:tensorflow:global_step/sec: 756.764
INFO:tensorflow:loss = 3.71776e+10, step =

INFO:tensorflow:global_step/sec: 780.42
INFO:tensorflow:loss = 5.17029e+09, step = 72901 (0.128 sec)
INFO:tensorflow:global_step/sec: 805.372
INFO:tensorflow:loss = 2.1874e+10, step = 73001 (0.128 sec)
INFO:tensorflow:global_step/sec: 805.381
INFO:tensorflow:loss = 1.92632e+10, step = 73101 (0.124 sec)
INFO:tensorflow:global_step/sec: 780.212
INFO:tensorflow:loss = 7.9752e+09, step = 73201 (0.128 sec)
INFO:tensorflow:global_step/sec: 780.202
INFO:tensorflow:loss = 1.80513e+10, step = 73301 (0.128 sec)
INFO:tensorflow:global_step/sec: 780.005
INFO:tensorflow:loss = 7.26654e+09, step = 73401 (0.124 sec)
INFO:tensorflow:global_step/sec: 805.604
INFO:tensorflow:loss = 3.18057e+10, step = 73501 (0.128 sec)
INFO:tensorflow:global_step/sec: 780.205
INFO:tensorflow:loss = 6.17752e+09, step = 73601 (0.128 sec)
INFO:tensorflow:global_step/sec: 780.005
INFO:tensorflow:loss = 6.01646e+09, step = 73701 (0.128 sec)
INFO:tensorflow:global_step/sec: 780.415
INFO:tensorflow:loss = 4.78722e+10, step = 7

INFO:tensorflow:global_step/sec: 805.376
INFO:tensorflow:loss = 1.50516e+10, step = 81001 (0.128 sec)
INFO:tensorflow:global_step/sec: 805.378
INFO:tensorflow:loss = 1.24686e+10, step = 81101 (0.124 sec)
INFO:tensorflow:global_step/sec: 713.334
INFO:tensorflow:loss = 1.88553e+10, step = 81201 (0.140 sec)
INFO:tensorflow:global_step/sec: 693.522
INFO:tensorflow:loss = 2.00436e+10, step = 81301 (0.144 sec)
INFO:tensorflow:global_step/sec: 734.315
INFO:tensorflow:loss = 4.37015e+10, step = 81401 (0.136 sec)
INFO:tensorflow:global_step/sec: 756.567
INFO:tensorflow:loss = 2.51657e+10, step = 81501 (0.132 sec)
INFO:tensorflow:global_step/sec: 734.315
INFO:tensorflow:loss = 4.69359e+10, step = 81601 (0.136 sec)
INFO:tensorflow:global_step/sec: 805.373
INFO:tensorflow:loss = 6.2653e+09, step = 81701 (0.120 sec)
INFO:tensorflow:global_step/sec: 780.212
INFO:tensorflow:loss = 9.18622e+09, step = 81801 (0.132 sec)
INFO:tensorflow:global_step/sec: 780.208
INFO:tensorflow:loss = 2.41578e+10, step =

INFO:tensorflow:global_step/sec: 734.314
INFO:tensorflow:loss = 1.51917e+10, step = 89101 (0.136 sec)
INFO:tensorflow:global_step/sec: 779.998
INFO:tensorflow:loss = 2.0765e+10, step = 89201 (0.128 sec)
INFO:tensorflow:global_step/sec: 780.423
INFO:tensorflow:loss = 1.57226e+10, step = 89301 (0.128 sec)
INFO:tensorflow:global_step/sec: 780.209
INFO:tensorflow:loss = 3.95867e+09, step = 89401 (0.128 sec)
INFO:tensorflow:global_step/sec: 780.205
INFO:tensorflow:loss = 9.02693e+09, step = 89501 (0.128 sec)
INFO:tensorflow:global_step/sec: 756.566
INFO:tensorflow:loss = 6.37011e+10, step = 89601 (0.132 sec)
INFO:tensorflow:global_step/sec: 756.379
INFO:tensorflow:loss = 4.78324e+10, step = 89701 (0.128 sec)
INFO:tensorflow:global_step/sec: 734.494
INFO:tensorflow:loss = 7.32336e+09, step = 89801 (0.140 sec)
INFO:tensorflow:global_step/sec: 713.335
INFO:tensorflow:loss = 2.25005e+10, step = 89901 (0.140 sec)
INFO:tensorflow:global_step/sec: 674.779
INFO:tensorflow:loss = 8.00318e+09, step =

INFO:tensorflow:global_step/sec: 780.423
INFO:tensorflow:loss = 1.05644e+10, step = 97201 (0.128 sec)
INFO:tensorflow:global_step/sec: 805.376
INFO:tensorflow:loss = 3.88191e+10, step = 97301 (0.128 sec)
INFO:tensorflow:global_step/sec: 805.375
INFO:tensorflow:loss = 8.4283e+09, step = 97401 (0.124 sec)
INFO:tensorflow:global_step/sec: 713.34
INFO:tensorflow:loss = 3.94612e+10, step = 97501 (0.140 sec)
INFO:tensorflow:global_step/sec: 713.333
INFO:tensorflow:loss = 2.32705e+10, step = 97601 (0.136 sec)
INFO:tensorflow:global_step/sec: 734.312
INFO:tensorflow:loss = 1.02346e+10, step = 97701 (0.140 sec)
INFO:tensorflow:global_step/sec: 713.319
INFO:tensorflow:loss = 4.84421e+10, step = 97801 (0.140 sec)
INFO:tensorflow:global_step/sec: 756.587
INFO:tensorflow:loss = 1.11586e+11, step = 97901 (0.132 sec)
INFO:tensorflow:global_step/sec: 713.329
INFO:tensorflow:loss = 7.41672e+10, step = 98001 (0.140 sec)
INFO:tensorflow:global_step/sec: 734.293
INFO:tensorflow:loss = 2.82001e+10, step = 

In [145]:
predict_input_func = tf.estimator.inputs.pandas_input_fn(x = X_test,
                                                        batch_size = 100,
                                                        num_epochs= 1,
                                                        shuffle=False)

In [146]:
pred_gen = model.predict(predict_input_func)
X_test.head()

flight_duration  stops  days_of_anticipation
4397          0.198647    2.0                  94.0
11106         0.206027    1.0                  40.0
17181         0.074723    1.0                 206.0
11746         0.015375    0.0                 230.0
12408         0.069496    1.0                 218.0

In [147]:
predictions = list(pred_gen)


INFO:tensorflow:Restoring parameters from C:\Users\guill\AppData\Local\Temp\tmpjd2_6urx\model.ckpt-100000


In [148]:
final_preds = []

for pred in predictions: 
    final_preds.append(pred['predictions'])

In [149]:
from sklearn.metrics import mean_squared_error

In [150]:
error = mean_squared_error(y_test, final_preds)**0.5
error

14563.395602575452

In [151]:
avg_error = error/len(X_test)
avg_error

2.1521199353591625

In [152]:
final_preds[0]

array([ 18057.0625], dtype=float32)

In [153]:
y_real_values = list(y_test)
final_preds[:10]

[array([ 18057.0625], dtype=float32),
 array([ 11466.01269531], dtype=float32),
 array([ 8567.28417969], dtype=float32),
 array([ 4939.10791016], dtype=float32),
 array([ 8712.67089844], dtype=float32),
 array([ 17028.44921875], dtype=float32),
 array([ 18748.20117188], dtype=float32),
 array([ 8582.29296875], dtype=float32),
 array([ 18281.87109375], dtype=float32),
 array([ 12682.18261719], dtype=float32)]

In [154]:
list(y_test)[:10]

[55474.0,
 7680.7199999999993,
 6524.0,
 1245.29,
 5186.0,
 22064.0,
 12917.0,
 6851.0,
 12937.0,
 5793.0]